Repository CodeDead/Advanced-PassGen, pull requests merged in 2022-10, with the labels that each got.

#6 Feature/export
  README.md
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/components/ExportDialog/index.jsx
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/nl_nl.json
  src/routes/Generate/index.jsx
Labels: enhancement

#9 Fix for platform
  .github/workflows/test.yml
Labels: enhancement

#10 Design enhancements
  README.md
  package.json
  src/components/App/index.jsx
  src/components/LoadingBar/index.jsx
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/nl_nl.json
  src/routes/Advanced/index.jsx
  src/routes/NotFound/index.jsx
Labels: design

#13 Fixed missing OK translation, code refactoring
  src/components/App/index.jsx
  src/components/ClippedDrawer/index.jsx
  src/components/MuiVirtualizedTable/index.jsx
  src/components/TopBar/index.jsx
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/nl_nl.json
  src/routes/About/index.jsx
  src/routes/Advisor/index.jsx
  src/routes/Generate/index.jsx
  src/routes/Settings/index.jsx
  src/utils/PasswordGenerator/index.js
Labels: enhancement

#15 Fixed an issue that caused incorrect number parsing, generate passwor…
  src/routes/Advanced/index.jsx
  src/routes/Home/index.jsx
  src/utils/PasswordGenerator/index.js
Labels: bug, enhancement

#16 German translation
  src/contexts/MainContextProvider/index.jsx
  src/languages/de_de.json
Labels: translations

#17 Added a language menu in the top bar and a setting to disable it
  package.json
  src/components/TopBar/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/languages/de_de.json
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/nl_nl.json
  src/reducers/MainReducer/Actions/actionTypes.js
  src/reducers/MainReducer/Actions/index.js
  src/reducers/MainReducer/index.js
  src/routes/Settings/index.jsx
  yarn.lock
Labels: enhancement, design

#18 Feature/native password generator
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src/components/App/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/reducers/MainReducer/Actions/actionTypes.js
  src/reducers/MainReducer/Actions/index.js
  src/reducers/MainReducer/index.js
  src/reducers/PasswordReducer/Actions/index.js
  src/reducers/PasswordReducer/index.js
  src/routes/Advanced/index.jsx
  src/routes/Generate/index.jsx
  src/routes/Home/index.jsx
  src/utils/PasswordGenerator/index.js
  yarn.lock
Labels: enhancement

#19 UI improvements for mobile
  src/components/ClippedDrawer/index.jsx
Labels: enhancement, design

#20 Added Russian, refactoring
  src/components/App/index.jsx
  src/components/ClippedDrawer/index.jsx
  src/components/TopBar/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/languages/ru_ru.json
  src/routes/About/index.jsx
  src/routes/Settings/index.jsx
Labels: enhancement, translations

#21 Added Japanese
  src/components/TopBar/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/languages/jp_jp.json
  src/routes/Settings/index.jsx
Labels: translations
