Repository CodeDead/Advanced-PassGen, pull requests merged in 2022-11, with the labels that each got.

#22 Added a setting to make the clipped drawer always visible
  package.json
  src/components/ClippedDrawer/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/languages/de_de.json
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/jp_jp.json
  src/languages/nl_nl.json
  src/languages/ru_ru.json
  src/reducers/MainReducer/Actions/actionTypes.js
  src/reducers/MainReducer/Actions/index.js
  src/reducers/MainReducer/index.js
  src/routes/Settings/index.jsx
  yarn.lock
Labels: enhancement

#23 Update rust version
  .github/workflows/release.yml
  .github/workflows/test.yml
  src-tauri/Cargo.toml
Labels: enhancement

#24 Release/v2.1.0
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/components/App/index.jsx
  src/components/ClippedDrawer/index.jsx
  src/components/TopBar/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/languages/de_de.json
  src/languages/en_us.json
  src/languages/fr_fr.json
  src/languages/jp_jp.json
  src/languages/nl_nl.json
  src/languages/ru_ru.json
  src/reducers/MainReducer/Actions/actionTypes.js
  src/reducers/MainReducer/Actions/index.js
  src/reducers/MainReducer/index.js
  src/reducers/PasswordReducer/Actions/index.js
  src/reducers/PasswordReducer/index.js
  src/routes/About/index.jsx
  src/routes/Advanced/index.jsx
  src/routes/Generate/index.jsx
  src/routes/Home/index.jsx
  src/routes/Settings/index.jsx
  src/utils/PasswordGenerator/index.js
  yarn.lock
Labels: enhancement, design, translations

#25 Add Simplified Chinese translation
  src/languages/zh_CN.json
Labels: translations

#26 Made Simplified Chinese translations available in the app
  src/components/TopBar/index.jsx
  src/contexts/MainContextProvider/index.jsx
  src/routes/Settings/index.jsx
Labels: translations

#29 Yarn upgrade, tauri upgrade, dependency upgrades
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  yarn.lock
Labels: dependencies
